# Project Title

In [1]:
#UNDERSTANDING ACCIDENTS PATTERNS

# Goals

In [2]:
#My project aims to find the lowest risk aeroplane and enhance avaiation safety by understanding 
#patterns in aviation accidents.

## Data

#import python libraries and the csv file to the notebook.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

In [4]:
df = pd.read_csv('AviationData.csv', encoding='ISO-8859-1')
df.head(3)

/tmp/ipykernel_27011/3877424389.py:1: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('AviationData.csv', encoding='ISO-8859-1')

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007

In [5]:
df.tail()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

## Methods

#Data cleaning.

In [7]:
df.isnull()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,True,...,False,True,False,True,True,True,False,False,False,False
3,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,False,False,True,True,True,False
88885,False,False,False,False,False,False,True,True,True,True,...,True,True,False,False,False,False,True,True,True,True
88886,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,True,False
88887,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,True,True,True,True
88888,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,False,False,True,True,True,False

In [8]:
df.isnull().sum().sum()

np.int64(565032)

In [9]:
df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

#Make the null values in the continous data 0 instead of dropping the row.

In [10]:
df['Total.Fatal.Injuries'] = pd.to_numeric(df['Total.Fatal.Injuries'], errors='coerce').fillna(0).astype(int)

In [11]:
df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries          0
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [12]:
for col in ['Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured']:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)

In [13]:
df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries          0
Total.Serious.Injuries        0
Total.Minor.Injuries          0
Total.Uninjured               0
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [14]:
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,88889.000000,88889.000000,88889.000000,88889.000000
mean,1.146585,0.564761,0.240491,0.309127,4.971245
std,0.446510,5.126649,1.434614,2.083715,27.002011
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

#Check for duplicates in the code.

In [15]:
duplicates = df[df.duplicated()]
print(len(duplicates))
duplicates.head()

0

Empty DataFrame
Columns: [Event.Id, Investigation.Type, Accident.Number, Event.Date, Location, Country, Latitude, Longitude, Airport.Code, Airport.Name, Injury.Severity, Aircraft.damage, Aircraft.Category, Registration.Number, Make, Model, Amateur.Built, Number.of.Engines, Engine.Type, FAR.Description, Schedule, Purpose.of.flight, Air.carrier, Total.Fatal.Injuries, Total.Serious.Injuries, Total.Minor.Injuries, Total.Uninjured, Weather.Condition, Broad.phase.of.flight, Report.Status, Publication.Date]
Index: []

[0 rows x 31 columns]

#Checking for extraneous values

In [16]:
for col in df.columns:
    print(col, '\n', df[col].value_counts(normalize=True).head(), '\n\n')

Event.Id
 Event.Id
20001214X45071    0.000034
20001212X19172    0.000034
20001206X01843    0.000022
20001208X09001    0.000022
20001213X32495    0.000022
Name: proportion, dtype: float64


Investigation.Type
 Investigation.Type
Accident    0.956418
Incident    0.043582
Name: proportion, dtype: float64


Accident.Number
 Accident.Number
WPR23LA045    0.000022
ERA22LA364    0.000022
DCA22WA089    0.000022
DCA22WA214    0.000022
WPR22FA309    0.000022
Name: proportion, dtype: float64


Event.Date
 Event.Date
1982-05-16    0.000281
1984-06-30    0.000281
2000-07-08    0.000281
1983-08-05    0.000270
1984-08-25    0.000270
Name: proportion, dtype: float64


Location
 Location
ANCHORAGE, AK      0.004885
MIAMI, FL          0.002251
ALBUQUERQUE, NM    0.002206
HOUSTON, TX        0.002173
CHICAGO, IL        0.002071
Name: proportion, dtype: float64


Country
 Country
United States     0.927647
Brazil            0.004218
Canada            0.004049
Mexico            0.004038
United Kingdom    0.003880
Name: proportion, dtype: float64


Latitude
 Latitude
332739N      0.000553
335219N      0.000524
32.815556    0.000494
334118N      0.000494
324934N      0.000465
Name: proportion, dtype: float64


Longitude
 Longitude
0112457W       0.000698
1114342W       0.000524
1151140W       0.000495
-104.673056    0.000495
-112.0825      0.000465
Name: proportion, dtype: float64


Airport.Code
 Airport.Code
NONE    0.029682
PVT     0.009674
APA     0.003192
ORD     0.002972
MRI     0.002733
Name: proportion, dtype: float64


Airport.Name
 Airport.Name
Private             0.004554
PRIVATE             0.004250
Private Airstrip    0.002903
NONE                0.002770
PRIVATE STRIP       0.002106
Name: proportion, dtype: float64


Injury.Severity
 Injury.Severity
Non-Fatal    0.766387
Fatal(1)     0.070168
Fatal        0.059871
Fatal(2)     0.042224
Incident     0.025248
Name: proportion, dtype: float64


Aircraft.damage
 Aircraft.damage
Substantial    0.748562
Destroyed      0.217317
Minor          0.032732
Unknown        0.001389
Name: proportion, dtype: float64


Aircraft.Category
 Aircraft.Category
Airplane      0.855360
Helicopter    0.106544
Glider        0.015734
Balloon       0.007155
Gyrocraft     0.005358
Name: proportion, dtype: float64


Registration.Number
 Registration.Number
NONE      0.003931
UNREG     0.001440
UNK       0.000149
USAF      0.000103
N20752    0.000091
Name: proportion, dtype: float64


Make
 Make
Cessna    0.250231
Piper     0.135422
CESSNA    0.055412
Beech     0.048747
PIPER     0.031984
Name: proportion, dtype: float64


Model
 Model
152          0.026656
172          0.019775
172N         0.013109
PA-28-140    0.010496
150          0.009336
Name: proportion, dtype: float64


Amateur.Built
 Amateur.Built
No     0.904547
Yes    0.095453
Name: proportion, dtype: float64


Number.of.Engines
 Number.of.Engines
1.0    0.840312
2.0    0.133796
0.0    0.014806
3.0    0.005833
4.0    0.005205
Name: proportion, dtype: float64


Engine.Type
 Engine.Type
Reciprocating    0.850073
Turbo Shaft      0.044124
Turbo Prop       0.041458
Turbo Fan        0.030333
Unknown          0.025075
Name: proportion, dtype: float64


FAR.Description
 FAR.Description
091                          0.568997
Part 91: General Aviation    0.202542
NUSN                         0.049464
NUSC                         0.031634
137                          0.031540
Name: proportion, dtype: float64


Schedule
 Schedule
NSCH    0.355587
UNK     0.325783
SCHD    0.318630
Name: proportion, dtype: float64


Purpose.of.flight
 Purpose.of.flight
Personal              0.597942
Instructional         0.128191
Unknown               0.082252
Aerial Application    0.056979
Business              0.048587
Name: proportion, dtype: float64


Air.carrier
 Air.carrier
Pilot                    0.015497
American Airlines        0.005406
United Airlines          0.005346
Delta Air Lines          0.003184
SOUTHWEST AIRLINES CO    0.002523
Name: proportion, dtype: float64


Total.Fatal.Injuries
 Total.Fatal.Injuries
0    0.799604
1    0.099934
2    0.058196
3    0.017876
4    0.012409
Name: proportion, dtype: float64


Total.Serious.Injuries
 Total.Serious.Injuries
0    0.852738
1    0.102656
2    0.031669
3    0.007076
4    0.002902
Name: proportion, dtype: float64


Total.Minor.Injuries
 Total.Minor.Injuries
0    0.825603
1    0.116100
2    0.040230
3    0.008820
4    0.004185
Name: proportion, dtype: float64


Total.Uninjured
 Total.Uninjured
0    0.402648
1    0.282386
2    0.179865
3    0.048521
4    0.029947
Name: proportion, dtype: float64


Weather.Condition
 Weather.Condition
VMC    0.915945
IMC    0.070808
UNK    0.010143
Unk    0.003104
Name: proportion, dtype: float64


Broad.phase.of.flight
 Broad.phase.of.flight
Landing        0.249951
Takeoff        0.202401
Cruise         0.166370
Maneuvering    0.131942
Approach       0.106053
Name: proportion, dtype: float64


Report.Status
 Report.Status
Probable Cause                                                                  0.748488
Foreign                                                                         0.024229
<br /><br />                                                                    0.002024
Factual                                                                         0.001757
The pilot's failure to maintain directional control during the landing roll.    0.000679
Name: proportion, dtype: float64


Publication.Date
 Publication.Date
25-09-2020    0.226564
26-09-2020    0.023550
03-11-2020    0.015376
31-03-1993    0.006017
25-11-2003    0.005272
Name: proportion, dtype: float64

df.duplicated().value_counts()

#Drop the duplicates but keep the first occurence.

In [17]:
df = df.drop_duplicates()
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2,0,0,0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4,0,0,0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3,0,0,0,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2,0,0,0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1,2,0,0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0,1,0,0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0,0,0,1,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0,0,0,0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0,1,0,1,NaN,NaN,NaN,30-12-2022

In [18]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
88884    False
88885    False
88886    False
88887    False
88888    False
Length: 88889, dtype: bool

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    88889 non-null  int64
 24  Total.Serious.Injuries  88889 non-null  int64
 25  Total.Minor.Injuries    88889 non-null  int64
 26  Total.Uninjured         88889 non-null  int64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(1), int64(4), object(26)
memory usage: 21.0+ MB

In [25]:
grouped_df = df.groupby('Year')
grouped_df . <TAB>

SyntaxError: invalid syntax (1021443792.py, line 2)

## Results

### Business Recommendation 1

### Business Recommendation 2

### Business Recommendation 3